APP_STL := c++_static
NDK_TOOLCHAIN_VERSION=clang

APP_CPPFLAGS := -frtti -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -std=c++11 -fsigned-char
APP_LDFLAGS := -latomic

APP_CPPFLAGS += -DCC_LUA_ENGINE_ENABLED=1
APP_CPPFLAGS += -DANYSDK_DEFINE=1

ifeq ($(NDK_DEBUG),1)
  APP_CPPFLAGS += -DCOCOS2D_DEBUG=1
  APP_OPTIM := debug
else
  APP_CPPFLAGS += -DNDEBUG
  APP_OPTIM := release
endif

CC_USE_CURL := 1
CC_USE_CCSTUDIO := 1
CC_USE_CCBUILDER := 1
CC_USE_SPINE := 1
CC_USE_PHYSICS := 1

ifeq ($(CC_USE_CURL),0)
APP_CPPFLAGS += -DCC_USE_CURL=0
endif
ifeq ($(CC_USE_CCSTUDIO),0)
APP_CPPFLAGS += -DCC_USE_CCSTUDIO=0
endif
ifeq ($(CC_USE_CCBUILDER),0)
APP_CPPFLAGS += -DCC_USE_CCBUILDER=0
endif
ifeq ($(CC_USE_SPINE),0)
APP_CPPFLAGS += -DCC_USE_SPINE=0
endif
ifeq ($(CC_USE_PHYSICS),0)
APP_CPPFLAGS += -DCC_USE_PHYSICS=0
endif
