system mp_hit_04
{
    keep_local                                  true
    technique 
    {
        visual_particle_quota                   10
        material                                PUMediaPack/Star_05
        renderer                                Billboard
        {
            billboard_type                      oriented_self
            billboard_rotation_type             vertex
        }
        emitter                                 Point 
        {
            emission_rate                       6
            angle                               360
            time_to_live                        0.3
            velocity                            1e-006
            duration                            0.1
            particle_width                      dyn_random
            {
                min                             60
                max                             200
            }
            particle_height                     dyn_random
            {
                min                             100
                max                             400
            }
            start_colour_range                  0.415686 0.678431 1 1
            end_colour_range                    0.643137 0.317647 1 1
            force_emission                      true
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 1
            time_colour                         1    0 0 0 1
            colour_operation                    multiply
        }
        affector                                Scale 
        {
            xyz_scale                           dyn_random
            {
                min                             800
                max                             1000
            }
        }
        observer                                OnClear 
        {
            observe_until_event                 true
            handler                             DoStopSystem 
            {
            }
        }
    }
}
