system timeShift
{
    technique 
    {
        visual_particle_quota                   20
        material                                PUMediaPack/Watch
        renderer                                Billboard
        {
        }
        emitter                                 Point 
        {
            emission_rate                       dyn_curved_linear
            {
                control_point                   0 0
                control_point                   0.2 10
                control_point                   3 0
            }
            angle                               360
            velocity                            dyn_random
            {
                min                             0.9
                max                             3
            }
            all_particle_dimensions             dyn_random
            {
                min                             3
                max                             12
            }
            colour                              1 0.88 0.26 1
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.5  1 1 1 1
            time_colour                         1    0 0 0 0
            colour_operation                    multiply
        }
        affector                                TextureRotator 
        {
            use_own_rotation                    true
            rotation_speed                      dyn_random
            {
                min                             -2
                max                             2
            }
        }
    }
    technique 
    {
        visual_particle_quota                   20
        material                                PUMediaPack/Hourglass
        renderer                                Billboard
        {
        }
        emitter                                 Point 
        {
            emission_rate                       dyn_curved_linear
            {
                control_point                   0 0
                control_point                   0.2 5
                control_point                   3 0
            }
            angle                               360
            velocity                            dyn_random
            {
                min                             0.9
                max                             3
            }
            all_particle_dimensions             dyn_random
            {
                min                             3
                max                             9
            }
            colour                              0.82 1 0.51 1
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.5  1 1 1 1
            time_colour                         1    0 0 0 0
            colour_operation                    multiply
        }
        affector                                TextureRotator 
        {
            use_own_rotation                    true
            rotation_speed                      dyn_random
            {
                min                             -2
                max                             2
            }
        }
    }
}
