// Application resource id define file.
 
// Original file name: test_sprite_res_def.h
// Generated by TOPS Builder:Project wizard,Date:2010-8-3
 

#ifndef  __test_sprite_RES_DEF_H__
#define  __test_sprite_RES_DEF_H__

#define  TEST_S_ID_Form1002   1073742826  /*"Main"*/

#endif
