// Application resource header file.
 
// Original file name: test_sprite_Res.h
// Generated by TOPS Builder:Project wizard,Date:2010-8-3
 


#define ResFolder1001 1001
#define Form1002 1002
