// Original file name: cocosTemplate_Res.h
// Generated by TOPS Builder 1.2.3.235 Date:2010-10-9

#define ResFolder1001 1001
#define Form1002 1002
#define CloseNormal 1003
#define CloseSelected 1004
