// Unicode string resource scrip file,DOT NOT include it.
 
// Original file name: cocosTemplateUnicodeScript.h
// Generated by TOPS Builder:Project wizard,Date:2010-09-27
 


#define TZD_CONV(x, y)
TZD_CONV(AppName_cocosTemplate, "cocosTemplate")

