s_pPathGrossini       = "Images/grossini.png"
s_pPathSister1        = "Images/grossinis_sister1.png"
s_pPathSister2        = "Images/grossinis_sister2.png"
s_pPathB1             = "Images/b1.png"
s_pPathB2             = "Images/b2.png"
s_pPathR1             = "Images/r1.png"
s_pPathR2             = "Images/r2.png"
s_pPathF1             = "Images/f1.png"
s_pPathF2             = "Images/f2.png"
s_pPathBlock          = "Images/blocks.png"
s_back                = "Images/background.png"
s_back1               = "Images/background1.png"
s_back2               = "Images/background2.png"
s_back3               = "Images/background3.png"
s_stars1              = "Images/stars.png"
s_stars2              = "Images/stars2.png"
s_fire                = "Images/fire.png"
s_snow                = "Images/snow.png"
s_streak              = "Images/streak.png"
s_PlayNormal          = "Images/btn-play-normal.png"
s_PlaySelect          = "Images/btn-play-selected.png"
s_AboutNormal         = "Images/btn-about-normal.png"
s_AboutSelect         = "Images/btn-about-selected.png"
s_HighNormal          = "Images/btn-highscores-normal.png"
s_HighSelect          = "Images/btn-highscores-selected.png"
s_Ball                = "Images/ball.png"
s_Paddle              = "Images/paddle.png"
s_pPathClose          = "Images/close.png"
s_MenuItem            = "Images/menuitemsprite.png"
s_SendScore           = "Images/SendScoreButton.png"
s_PressSendScore      = "Images/SendScoreButtonPressed.png"
s_Power               = "Images/powered.png"
s_AtlasTest           = "Images/atlastest.png"

-- tilemaps resource
s_TilesPng            = "TileMaps/tiles.png"
s_LevelMapTga         = "TileMaps/levelmap.tga"

-- spine test resource
s_pPathSpineBoyJson       = "spine/spineboy.json"
s_pPathSpineBoyAtlas       = "spine/spineboy.atlas"

-- fonts resource
s_markerFeltFontPath   = "fonts/Marker Felt.ttf"
s_arialPath            = "fonts/arial.ttf"
s_thonburiPath         = "fonts/Thonburi.ttf"
s_tahomaPath           = "fonts/tahoma.ttf"
