// Application application header file.
 
// Original file name: cocosTemplateApp.h
// Generated by TOPS Builder:Project wizard,Date:2010-09-27
 

#ifndef  _APP_DELEGATE_H_
#define  _APP_DELEGATE_H_

#include "CCXApplication.h"
#include "CCXEGLView.h"

class  AppDelegate  :  public cocos2d::CCXApplication
{
public:
	AppDelegate();
	~AppDelegate();

	virtual bool    initCocos2d();
	virtual Boolean EventHandler(EventType * pEvent);
    virtual void    applicationDidEnterBackground();
    virtual void    applicationWillEnterForeground();

protected:
    TRectangle              m_rcWnd;
    cocos2d::CCXEGLView *   m_pMainWnd;
};
 

#endif // _APP_DELEGATE_H_

