// Application main file.
 
// Original file name: Cocos2dSimpleGameEntry.cpp
// Generated by TOPS Builder:Project wizard,Date:2010-10-12
 

#include  "Cocos2dSimpleGameAppDelegate.h"
#include  "cocos2dsimplegame_res_c.h"

const  ResourceRegisterEntry		ResRegList_Cocos2dSimpleGame[]  =
{
	TG_RESOURCE_DEFINE
};

const  AppResourceEntry		Cocos2dSimpleGameResourceEntry  =
{
	(ResourceRegisterEntry*)ResRegList_Cocos2dSimpleGame,                    //  res  list  in  this  app
		sizeof(ResRegList_Cocos2dSimpleGame) /  sizeof(ResourceRegisterEntry),    //number  of  item  in  res
};

Int32 TG3AppMain(const TUChar * pAppID, UInt32 nCmd, void * pCmdParam)
{
	AppDelegate app;
    app.Run();

    return 1;
}


