/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by "generate_jsb.py -c chipmunk_jsb.ini" on 2013-03-05
* Script version: v0.6
*/

var cp = cp || {};
cp.ALLOW_PRIVATE_ACCESS	= 0x1;
cp.ALL_LAYERS	= 0xffffffff;
cp.BUFFER_BYTES	= 0x8000;
cp.CIRCLE_SHAPE	= 0x0;
cp.HASH_COEF	= 0xc75f71e1;
cp.MAX_CONTACTS_PER_ARBITER	= 0x4;
cp.NO_GROUP	= 0x0;
cp.NUM_SHAPES	= 0x3;
cp.POLY_SHAPE	= 0x2;
cp.SEGMENT_SHAPE	= 0x1;
cp.USE_CGPOINTS	= 0x1;
cp.USE_DOUBLES	= 0x0;
cp.VERSION_MAJOR	= 0x6;
cp.VERSION_MINOR	= 0x1;
cp.VERSION_RELEASE	= 0x1;
