// Application resource id define file.
 
// Original file name: test_uphone_res_def.h
// Generated by TOPS Builder:Project wizard,Date:2010-7-26
 

#ifndef  __test_uphone_RES_DEF_H__
#define  __test_uphone_RES_DEF_H__

#define  TEST_U_ID_Form1002   1073742826  /*"Main"*/

#endif
