// Application main header  file.
 
// Original file name: test_spriteEntry.h
// Generated by TOPS Builder:Project wizard,Date:2010-8-3
 


#ifndef  __test_sprite_Main_H__
#define  __test_sprite_Main_H__
#include "TG3.h"

#endif

