// Unicode string resource scrip file,DOT NOT include it.
 
// Original file name: test_spriteUnicodeScript.h
// Generated by TOPS Builder:Project wizard,Date:2010-8-3
 


#define TZD_CONV(x, y)
TZD_CONV(AppName_test_sprite, "test_sprite")

