// Application main form file.

// Original file name: TestSpriteMainForm.h
// Generated by TOPS Builder:Project wizard,Date:2010-7-27
 

 
#ifndef  __TestSprite_MainForm_H__
#define  __TestSprite_MainForm_H__
#include "TG3.h"

class TMainForm : public TWindow
{
public:

	TMainForm(TApplication * pApp);

	~TMainForm(void);

	virtual Boolean EventHandler(TApplication * pApp, EventType * pEvent);
protected:
	Boolean SetBackGround();

	Boolean m_bGLESInit;
	TBitmap *m_gbitmap;
	INT32 m_nTimerID;
};
 

#endif

