#ifndef __EDITOR_SUPPORT_COCOSBUILDER_H__
#define __EDITOR_SUPPORT_COCOSBUILDER_H__

#include "cocosbuilder/CCBAnimationManager.h"
#include "cocosbuilder/CCBFileLoader.h"
#include "cocosbuilder/CCBKeyframe.h"
#include "cocosbuilder/CCBMemberVariableAssigner.h"
#include "cocosbuilder/CCBReader.h"
#include "cocosbuilder/CCBSelectorResolver.h"
#include "cocosbuilder/CCBSequence.h"
#include "cocosbuilder/CCBSequenceProperty.h"
#include "cocosbuilder/CCControlButtonLoader.h"
#include "cocosbuilder/CCControlLoader.h"
#include "cocosbuilder/CCLabelBMFontLoader.h"
#include "cocosbuilder/CCLabelTTFLoader.h"
#include "cocosbuilder/CCLayerColorLoader.h"
#include "cocosbuilder/CCLayerGradientLoader.h"
#include "cocosbuilder/CCLayerLoader.h"
#include "cocosbuilder/CCMenuItemImageLoader.h"
#include "cocosbuilder/CCMenuItemLoader.h"
#include "cocosbuilder/CCMenuLoader.h"
#include "cocosbuilder/CCNode+CCBRelativePositioning.h"
#include "cocosbuilder/CCNodeLoader.h"
#include "cocosbuilder/CCNodeLoaderLibrary.h"
#include "cocosbuilder/CCNodeLoaderListener.h"
#include "cocosbuilder/CCParticleSystemQuadLoader.h"
#include "cocosbuilder/CCScale9SpriteLoader.h"
#include "cocosbuilder/CCScrollViewLoader.h"
#include "cocosbuilder/CCSpriteLoader.h"

#endif // __EDITOR_SUPPORT_COCOSBUILDER_H__
