system flareShield
{
    technique 
    {
        visual_particle_quota                   200
        emitted_emitter_quota                   15
        material                                PUMediaPack/Flare_05
        renderer                                Billboard
        {
        }
        emitter                                 Point 
        {
            emission_rate                       3
            angle                               0
            velocity                            4.5
            duration                            4
            emits                               emitter_particle CircleEmitter
        }
        emitter                                 Circle CircleEmitter
        {
            emission_rate                       20
            angle                               360
            time_to_live                        dyn_random
            {
                min                             0.2
                max                             1
            }
            velocity                            0.15
            all_particle_dimensions             dyn_random
            {
                min                             0.9
                max                             2.4
            }
            keep_local                          true
            direction                           0 0 0
            colour                              0.7 0.8 1 1
            radius                              3
        }
        affector                                Vortex 
        {
            rotation_axis                       0 1 0
            rotation_speed                      7
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.8  1 1 1 1
            time_colour                         1    0 0 0 0
            colour_operation                    multiply
        }
        observer                                OnTime 
        {
            observe_until_event                 true
            handler                             DoEnableComponent 
            {
                enable_component                observer_component OnExpireObserver true
            }
            since_start_system                  true
            on_time                             greater_than 4
        }
        observer                                OnExpire OnExpireObserver
        {
            enabled                             false
            handler                             DoPlacementParticle 
            {
                force_emitter                   ExplodeEmitter
            }
        }
    }
    technique 
    {
        visual_particle_quota                   200
        emitted_emitter_quota                   30
        material                                PUMediaPack/Flare_05
        renderer                                Billboard
        {
        }
        emitter                                 Point ExplodeEmitter
        {
            emission_rate                       0
            angle                               0
            time_to_live                        dyn_random
            {
                min                             0.3
                max                             1
            }
            direction                           0 0 0
            emits                               emitter_particle ExplodeFlares
        }
        emitter                                 Point ExplodeFlares
        {
            emission_rate                       5
            angle                               360
            time_to_live                        1
            velocity                            6
            all_particle_dimensions             dyn_random
            {
                min                             1.5
                max                             1.8
            }
            colour                              0.7 0.8 1 1
        }
        observer                                OnClear 
        {
            handler                             DoStopSystem 
            {
            }
        }
    }
}
