system hypno
{
    technique 
    {
        visual_particle_quota                   200
        material                                ParticleUniverse/Swirl_02
        default_particle_width                  6
        default_particle_height                 6
        renderer                                Billboard
        {
        }
        emitter                                 Circle 
        {
            emission_rate                       40
            time_to_live                        dyn_random
            {
                min                             2
                max                             5
            }
            velocity                            0.9
            all_particle_dimensions             dyn_random
            {
                min                             3
                max                             12
            }
            direction                           0 0 0
            colour                              1 0.22 0.22 1
            auto_direction                      true
            radius                              6
            normal                              0 0 1
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.8  1 1 1 1
            time_colour                         1    0 0 0 0
            colour_operation                    multiply
        }
        affector                                TextureRotator 
        {
            rotation                            dyn_random
            {
                min                             0
                max                             180
            }
            rotation_speed                      dyn_random
            {
                min                             5
                max                             20
            }
        }
    }
}
