system lineStreak
{
    category                                    LightFX
    technique 
    {
        keep_local                              true
        visual_particle_quota                   250
        material                                PUMediaPack/Pentagram_02
        renderer                                Billboard
        {
            billboard_type                      oriented_self
        }
        emitter                                 Point 
        {
            emission_rate                       200
            angle                               360
            time_to_live                        1
            velocity                            dyn_random
            {
                min                             3
                max                             7.5
            }
            particle_width                      dyn_random
            {
                min                             0.3
                max                             1.4
            }
            particle_height                     dyn_random
            {
                min                             6
                max                             12
            }
            colour                              1 0.84 0.45 1
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.8  1 1 1 1
            time_colour                         1    0 0 0 0
            colour_operation                    multiply
        }
    }
}
