system example_029
{
    category                                    Examples_21_30
    technique 
    {
        visual_particle_quota                   2000
        emitted_affector_quota                  200
        material                                ParticleUniverse/Interpolate
        default_particle_width                  1.8
        default_particle_height                 1.8
        renderer                                Billboard
        {
            texture_coords_rows                 6
            texture_coords_columns              6
        }
        emitter                                 Point 
        {
            angle                               360
            time_to_live                        dyn_random
            {
                min                             2
                max                             5
            }
            velocity                            dyn_random
            {
                min                             3.6
                max                             4.8
            }
        }
        affector                                Scale 
        {
            xyz_scale                           0.6
        }
        affector                                TextureAnimator 
        {
            time_step                           0.1
            end_texture_coords_range            35
            texture_start_random                false
        }
    }
}
