#ifndef _RESOURCE_HANDLE_H_
#define _RESOURCE_HANDLE_H_

struct AppResourceEntry;
class  TResourceLib;

/**
@class ResourceHandle
@brief Object that contains the ResourceEntry
*/
class ResourceHandle
{
public:
    ResourceHandle();
    ~ResourceHandle();

    /**
    @brief Set the ResourceEntry
    */
    void setResourceEntry(const void* pResEntry);

    /**
    @brief Release the ResourceEntry
    */
    void release();

    /**
    @brief Load the file data from ResourceEntry
    @param[in] nResID The resource id which is generated by TOPS Builder
    @param[out] nLen  The size of file data.
    @return The pointer of file data.
    */
    const void* LoadConstRawData(int nResID, unsigned int* nLen);

private:
    TResourceLib* m_pResLib;
};

#endif
