
local UmengShareMedia = {
	SINA = "SINA",
	QZONE = "QZONE",
	QQ = "QQ",
	RENREN = "RENREN",
	WEIXIN = "WEIXIN",
	WEIXIN_CIRCLE = "WEIXIN_CIRCLE",
	TENCENT = "TENCENT",
	DOUBAN = "DOUBAN",
	SMS = "SMS",
	EMAIL = "EMAIL",
	GOOGLEPLUS = "GOOGLEPLUS",
	FACEBOOK = "FACEBOOK",
	TWITTER = "TWITTER",
	LAIWANG = "LAIWANG",
	LAIWANG_DYNAMIC = "LAIWANG_DYNAMIC",
	YIXIN = "YIXIN",
	YIXIN_CIRCLE = "YIXIN_CIRCLE",
	INSTAGRAM = "INSTAGRAM",
	GENERIC = "GENERIC",
}

return UmengShareMedia
