// Application application cpp file.
 
// Original file name: test_uphoneApp.cpp
// Generated by TOPS Builder:Project wizard,Date:2010-7-26
 

#include  "test_uphoneApp.h"
#include  "test_uphoneMainForm.h"
Ttest_uphoneApp::Ttest_uphoneApp()
{

}

Ttest_uphoneApp::~Ttest_uphoneApp()
{

}

Boolean  Ttest_uphoneApp::EventHandler(EventType*  pEvent)
{
	Boolean     bHandled = FALSE;

	switch(pEvent->eType)
	{
	case EVENT_AppLoad:
		{
			TMainForm *pWin = new TMainForm(this);
			if (pWin)
			{
				SetActiveWindow(pWin);
			}
			else
			{	// 窗口创建失败，退出应用。
				SendStopEvent();
			}
		}
		bHandled = TRUE;
		break;

	case EVENT_AppStopNotify:
		{
			
		}
		bHandled = FALSE;
		break;
	}
	if (FALSE == bHandled) 
	{
		return TApplication::EventHandler(pEvent);
	}

	return bHandled;
}
