// Application main form file.
 
// Original file name: test_uphoneMainForm.h
// Generated by TOPS Builder:Project wizard,Date:2010-7-26
 

 
#ifndef  __test_uphone_MainForm_H__
#define  __test_uphone_MainForm_H__
#include "TG3.h"

class TMainForm : public TWindow
{
public:

	TMainForm(TApplication * pApp);

	~TMainForm(void);

public:
	virtual Boolean EventHandler(TApplication * pApp, EventType * pEvent);
protected:
};
 

#endif

