// Unicode string resource file
 
// Original file name: test_uphoneUnicodeScript_str.h
// Generated by TOPS Builder:Project wizard,Date:2010-7-26
 

#ifndef  __test_uphone_STR_STR_H__
#define  __test_uphone_STR_STR_H__


#define  AppName_test_uphone__N  \
    "A\x00p\x00p\x00_\x00T\x00\x65\x00s\x00t\x00"
#define  AppName_test_uphone__C  \
    AppName_test_uphone__N"\x00\x00"
#define  AppName_test_uphone \
    ((const  unsigned  short  *)(AppName_test_uphone__C))
#define  AppName_test_uphone__N16  \
    0x0041,0x0070,0x0070,0x005f,0x0054,0x0065,0x0073,0x0074
#define  AppName_test_uphone_16  \
    {AppName_test_uphone__N16,0x0000}
// 原始串信息：
//  test_uphone


#endif

