/****************************************************************************
 Copyright (c) 2012 cocos2d-x.org
 Copyright (c) 2012 XiaoLong Zhang, Chukong Inc.
 
 http://www.cocos2d-x.org
 
 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:
 
 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.
 
 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 THE SOFTWARE.
 ****************************************************************************/


#ifndef __CCB_READER_H__
#define __CCB_READER_H__

#include "cocos2d.h"

#define kCCBVersion 2

NS_CC_EXT_BEGIN

/**
 * @brief Parse CCBI file which is generated by CocosBuilder
 */
class CC_DLL CCBReader : public CCObject {        
    private:    
        unsigned char * mBytes;
        int mCurrentByte;
        int mCurrentBit;
    
        std::vector<std::string> * mStringCache;

    public:   
        /* Constructor. */
        CCBReader();
        /* Destructor. */
        ~CCBReader();

        CCNode * readNodeGraphFromFile(const char* ccbFileName, CCNode* owner = NULL);
            
    private:
        bool readHeader();
        bool readStringCache();
        CCNode * readNodeGraph();
    
        bool getBit();
        void alignBits();
        int readInt(bool pSign);
};

NS_CC_EXT_END

#endif // __CCB_READER_H__