// Application main form file.
 
// Original file name: TestAudioEngineMainForm.h
// Generated by TOPS Builder:Project wizard,Date:2010-9-29
 

 
#ifndef  __TestAudioEngine_MainForm_H__
#define  __TestAudioEngine_MainForm_H__
#include "TG3.h"

class TMainForm : public TWindow
{
public:

	TMainForm(TApplication * pApp);

	~TMainForm(void);

public:
	virtual Boolean EventHandler(TApplication * pApp, EventType * pEvent);
    Boolean CtrlSelected(TApplication * pApp, EventType * pEvent);
protected:
    int m_nEffect2ID;
};
 

#endif

