// Unicode string resource file
 
// Original file name: HelloWorldUnicodeScript_str.h
// Generated by TOPS Builder:Project wizard,Date:2010-11-27
 

#ifndef  __HelloWorld_STR_STR_H__
#define  __HelloWorld_STR_STR_H__


#define  AppName_HelloWorld__N  \
    "A\x00p\x00p\x00_\x00T\x00\x65\x00s\x00t\x00"
#define  AppName_HelloWorld__C  \
    AppName_HelloWorld__N"\x00\x00"
#define  AppName_HelloWorld \
    ((const  unsigned  short  *)(AppName_HelloWorld__C))
#define  AppName_HelloWorld__N16  \
    0x0041,0x0070,0x0070,0x005f,0x0054,0x0065,0x0073,0x0074
#define  AppName_HelloWorld_16  \
    {AppName_HelloWorld__N16,0x0000}
// 原始串信息：
//  HelloWorld


#endif

