# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ v4, v3 ]
  pull_request:
    branches: [ v4, v3 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ubuntu-18_04:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: python download-deps.py --r no
      - run: echo -e "y" | bash build/install-deps-linux.sh
      - run: cmake -B b -S .
      - run: cmake --build b

  # https://github.com/cocos2d/cocos2d-x/issues/20471
  # ubuntu-20_04:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: python download-deps.py --r no
  #     - run: echo -e "y" | bash build/install-deps-linux.sh
  #     - run: cmake -B b -S .
  #     - run: cmake --build b

  windows-2019:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - run: python download-deps.py --r no
      - run: cmake -B b -S . -G "Visual Studio 16 2019" -A Win32
      - run: cmake --build b

  windows-2022:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - run: python download-deps.py --r no
      - run: cmake -B b -S . -G "Visual Studio 17 2022" -A Win32
      - run: cmake --build b

  macos-10_15:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - run: python download-deps.py --r no
      - run: cmake -B b -S . -GXcode
      - run: cmake --build b --target cpp-tests

  macos-11:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - run: python download-deps.py --r no
      - run: cmake -B b -S . -GXcode
      - run: cmake --build b --target cpp-tests

  ios_macos-10_15:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - run: python download-deps.py --r no
      - run: cmake -B b -S . -GXcode -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_SYSROOT=iphonesimulator -DCMAKE_SYSTEM_PROCESSOR=arm64
      - run: cmake --build b --config Release --target cpp-tests -- -quiet

  ios_macos-11:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - run: python download-deps.py --r no
      - run: cmake -B b -S . -GXcode -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_SYSROOT=iphonesimulator -DCMAKE_SYSTEM_PROCESSOR=arm64
      - run: cmake --build b --config Release --target cpp-tests -- -quiet -destination "platform=iOS Simulator,name=iPhone Retina (4-inch)"

  android_windows-2019:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - run: python download-deps.py --r no
      - run: ./gradlew assembleRelease -PPROP_BUILD_TYPE=cmake --info
        shell: bash
        working-directory: tests/cpp-tests/proj.android

  android_ubuntu-20_04:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: python download-deps.py --r no
      - run: ./gradlew assembleRelease -PPROP_BUILD_TYPE=cmake --info
        shell: bash
        working-directory: tests/cpp-tests/proj.android
