// Original file name: [!output PROJECT_NAME_LOWER]_Res.h
// Generated by Cocos2d-wophone Wizard Date: [!output CC_CURRENT_DATE]

#ifndef __[!output PROJECT_NAME_UPPER]_RES_DEF_H__
#define __[!output PROJECT_NAME_UPPER]_RES_DEF_H__

#define ResFolder1001 1001
#define CloseNormal 1002
#define CloseSelected 1003

#endif

